name: Upload Managed Beta (2GP)
on:
    push:
        branches:
            - 'main'
jobs:
    upload-managed-beta:
        name: 'Upload Managed Beta'
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - uses: cumulus-actions/release-beta-2gp@v1
              with:
                  dev-hub-auth-url: '${{ secrets.DEV_HUB_AUTH_URL }}'
                  cumulusci-version: '3.81.0'
                  sfdx-version: '7.209.6'
                  org-name: beta
    beta-test:
        name: 'Beta Test'
        needs:
            - upload-managed-beta
        runs-on: ubuntu-latest
        steps:
            - uses: cumulus-actions/beta-test@v1
              with:
                  dev-hub-auth-url: '${{ secrets.DEV_HUB_AUTH_URL }}'
                  cumulusci-version: '3.81.0'
                  sfdx-version: '7.209.6'
